#!/usr/bin/env ruby

s = File.read('./input.txt')

has_visited_basement = false
char_idx = 0
out = s.split('').reduce(0) do|floor, char|
  if char.eql?('(')
    floor += 1
  else
    floor -= 1
  end

  char_idx += 1
  if floor.negative? and !has_visited_basement
    has_visited_basement = true
    puts "char_idx: #{char_idx} takes Santa to basement"
  end

  floor
end

# 137 was too low!
# Oh, was missing the last bracket :P

puts out
