#!/usr/bin/env ruby

f = File.read('./input.txt')

# Ugly hash so don't have to stringify keys
$numbers = {
  'one'   => '1',
  'two'   => '2',
  'three' => '3',
  'four'  => '4',
  'five'  => '5',
  'six'   => '6',
  'seven' => '7',
  'eight' => '8',
  'nine'  => '9',
}

# Taxonomy
#   1   = dig = digit
#   one = alp = alpha
def extract_first_number(line)
  # Get idx of first digit (always present)
  # and first alpha, and return first one in line
  first_digit_idx = line.index(/\d/)
  first_alpha_idx = 999
  alpha_indices = []
  $numbers.keys.each do |key|

    idx = line.index(key)
    if !idx.nil?
      alpha_indices << {idx: idx, key: key}
    end
  end

  # No alpha numbers
  if !alpha_indices.empty?
    first_alpha_idx = alpha_indices.min_by { |ind| ind[:idx] }[:idx]
  end

  puts [alpha_indices, first_digit_idx , first_alpha_idx].to_s
  if first_digit_idx < first_alpha_idx
    line[first_digit_idx]
  else
    key = alpha_indices.min_by { |ind| ind[:idx] }[:key]
    $numbers[key]
  end
end

def extract_last_number(line)
  last_digit_idx = line.rindex(/\d/) # Oh neat
  last_alpha_idx = -999
  alpha_indices = []
  $numbers.keys.each do |key|

    puts "Looking for index of #{key} in #{line}"
    idx = line.index(key)
    if !idx.nil?
      puts "\tfound #{idx}"
      alpha_indices << {idx: idx, key: key}
    end
  end

  # No alpha numbers
  if !alpha_indices.empty?
    last_alpha_idx = alpha_indices.max_by { |ind| ind[:idx] }[:idx]
  end

  puts [alpha_indices, last_digit_idx , last_alpha_idx].to_s
  if last_digit_idx > last_alpha_idx
    line[last_digit_idx]
  else
    key = alpha_indices.max_by { |ind| ind[:idx] }[:key]
    $numbers[key]
  end
end

out = f.split("\n").reduce(0) do|sum, line|
  #
  # NOTE OK new new idea: bail at first number,
  # reverse, and repeat. No need to xform anything.

  first_num = extract_first_number(line)
  last_num = extract_last_number(line)

  sum += (first_num + last_num).to_i

  puts "#{sum} += (#{first_num} + #{last_num}) // #{line}"

  sum
end

# XXX 59587 too high
# XXX 53326 too loww
# XXX 54041 "not the right answer" :( darn
puts "Result: #{out}"

